### ISSUE TITLE
Расширение возможностей фильтрации

### ISSUE THREAD

**Issue by ruafelianna** [pfilsx/DataGridBundle#1]
Добрый день!

Просьба добавить возможность фильтрации для поля связанной таблицы через текстовый ввод, а не только через выпадающий список.

**Comment by pfilsx** [comment]
@ruafelianna, добрый день!
Для любого столбца можно указать любой удобный Вам фильтр, в том числе текстовый. Для применения фильтрации в версии 1.6.2 добавлен метод кастомной фильтрации `DataGridFiltersBuilder::addCustomFilter(string $attribute, callable $callback)`, callback которого принимает три параметра 
```
&$criteria - ссылка на объект Doctrine\Common\Collections\Criteria, используемый для фильтрации 
$attribute - наименование аттрибута 
$value - текущее значение фильтра
```

**Comment by ruafelianna** [comment]
Спасибо большое! :)
